python3 miniob_test.py \
        --db-base-dir=../../build/ \
        --db-config=../../etc/observer.ini \
        --test-case-dir=./test  \
        --test-case-scores=case-scores.json \
        --test-result-dir=result \
        --test-result-tmp-dir=./result_tmp \
        --use-unix-socket \
        --code-type=none \
        --target-dir=./miniob \
        --log=stdout \
